GET http://localhost:3001/api/personal

###

GET http://localhost:3001/api/credenciales/correo/carlos.perez@example.com

###

GET http://localhost:3001/api/credenciales/auth/carlos.perez@example.com/asd

###

GET http://localhost:3001/api/configuraciones/1

###

POST http://localhost:3001/api/credenciales
Content-Type: application/json

{
    "correo": "asdasdasdasda@hotmail.com",
    "contrasenia": "asdasdasd",
    "usuario": 17
}

###
POST http://localhost:3001/api/personal
Content-Type: application/json

{
    "nombre": "purororor",
    "direccion": "TEC DE CULIACAN",
    "telefono": "1237890",
    "estatus": 7
}

###

GET http://localhost:3001/api/software

###
POST http://localhost:3001/api/software
Content-Type: application/json

{
    "nombre": "testing",
    "desarrollador": "testeooo",
    "tipo": "holaholahola",
    "licencia": "MITasdasd",
    "version": "1.999999",
    "descripcion": "lorem ipsum dolor sit amet"
}

###
DELETE http://localhost:3001/api/software
Content-Type: application/json

{
    "id": 7
}

###

PUT http://localhost:3001/api/roles
Content-Type: application/json

{
    "id":5,
    "nombre": "Docente"
}